/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ASplatRouteImport } from './routes/a.$'
import { Route as ApiPublicHooksAnnounceRouteImport } from './routes/api/public/hooks/announce'
import { Route as ApiPublicHooksDeliverRouteImport } from './routes/api/public/hooks/deliver'
import { Route as ApiPublicHooksHeartbeatRouteImport } from './routes/api/public/hooks/heartbeat'
import { Route as ApiPublicHooksRecoverRouteImport } from './routes/api/public/hooks/recover'
import { Route as ApiPublicHooksSupportBotRouteImport } from './routes/api/public/hooks/support-bot'
import { Route as ApiPublicHooksSyncRouteImport } from './routes/api/public/hooks/sync'
import { Route as ApiPublicHooksTelegramRouteImport } from './routes/api/public/hooks/telegram'
import { Route as ApiPublicMediaSplatRouteImport } from './routes/api/public/media/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ASplatRoute = ASplatRouteImport.update({
  id: '/a/$',
  path: '/a/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksAnnounceRoute = ApiPublicHooksAnnounceRouteImport.update({
  id: '/api/public/hooks/announce',
  path: '/api/public/hooks/announce',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksDeliverRoute = ApiPublicHooksDeliverRouteImport.update({
  id: '/api/public/hooks/deliver',
  path: '/api/public/hooks/deliver',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksHeartbeatRoute = ApiPublicHooksHeartbeatRouteImport.update({
  id: '/api/public/hooks/heartbeat',
  path: '/api/public/hooks/heartbeat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRecoverRoute = ApiPublicHooksRecoverRouteImport.update({
  id: '/api/public/hooks/recover',
  path: '/api/public/hooks/recover',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSupportBotRoute =
  ApiPublicHooksSupportBotRouteImport.update({
    id: '/api/public/hooks/support-bot',
    path: '/api/public/hooks/support-bot',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyncRoute = ApiPublicHooksSyncRouteImport.update({
  id: '/api/public/hooks/sync',
  path: '/api/public/hooks/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksTelegramRoute = ApiPublicHooksTelegramRouteImport.update({
  id: '/api/public/hooks/telegram',
  path: '/api/public/hooks/telegram',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMediaSplatRoute = ApiPublicMediaSplatRouteImport.update({
  id: '/api/public/media/$',
  path: '/api/public/media/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/policies': typeof PoliciesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/a/$': typeof ASplatRoute
  '/api/public/hooks/announce': typeof ApiPublicHooksAnnounceRoute
  '/api/public/hooks/deliver': typeof ApiPublicHooksDeliverRoute
  '/api/public/hooks/heartbeat': typeof ApiPublicHooksHeartbeatRoute
  '/api/public/hooks/recover': typeof ApiPublicHooksRecoverRoute
  '/api/public/hooks/support-bot': typeof ApiPublicHooksSupportBotRoute
  '/api/public/hooks/sync': typeof ApiPublicHooksSyncRoute
  '/api/public/hooks/telegram': typeof ApiPublicHooksTelegramRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/policies': typeof PoliciesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/a/$': typeof ASplatRoute
  '/api/public/hooks/announce': typeof ApiPublicHooksAnnounceRoute
  '/api/public/hooks/deliver': typeof ApiPublicHooksDeliverRoute
  '/api/public/hooks/heartbeat': typeof ApiPublicHooksHeartbeatRoute
  '/api/public/hooks/recover': typeof ApiPublicHooksRecoverRoute
  '/api/public/hooks/support-bot': typeof ApiPublicHooksSupportBotRoute
  '/api/public/hooks/sync': typeof ApiPublicHooksSyncRoute
  '/api/public/hooks/telegram': typeof ApiPublicHooksTelegramRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/policies': typeof PoliciesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/a/$': typeof ASplatRoute
  '/api/public/hooks/announce': typeof ApiPublicHooksAnnounceRoute
  '/api/public/hooks/deliver': typeof ApiPublicHooksDeliverRoute
  '/api/public/hooks/heartbeat': typeof ApiPublicHooksHeartbeatRoute
  '/api/public/hooks/recover': typeof ApiPublicHooksRecoverRoute
  '/api/public/hooks/support-bot': typeof ApiPublicHooksSupportBotRoute
  '/api/public/hooks/sync': typeof ApiPublicHooksSyncRoute
  '/api/public/hooks/telegram': typeof ApiPublicHooksTelegramRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/policies'
    | '/sitemap.xml'
    | '/dashboard'
    | '/a/$'
    | '/api/public/hooks/announce'
    | '/api/public/hooks/deliver'
    | '/api/public/hooks/heartbeat'
    | '/api/public/hooks/recover'
    | '/api/public/hooks/support-bot'
    | '/api/public/hooks/sync'
    | '/api/public/hooks/telegram'
    | '/api/public/media/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/policies'
    | '/sitemap.xml'
    | '/dashboard'
    | '/a/$'
    | '/api/public/hooks/announce'
    | '/api/public/hooks/deliver'
    | '/api/public/hooks/heartbeat'
    | '/api/public/hooks/recover'
    | '/api/public/hooks/support-bot'
    | '/api/public/hooks/sync'
    | '/api/public/hooks/telegram'
    | '/api/public/media/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/policies'
    | '/sitemap.xml'
    | '/_authenticated/dashboard'
    | '/a/$'
    | '/api/public/hooks/announce'
    | '/api/public/hooks/deliver'
    | '/api/public/hooks/heartbeat'
    | '/api/public/hooks/recover'
    | '/api/public/hooks/support-bot'
    | '/api/public/hooks/sync'
    | '/api/public/hooks/telegram'
    | '/api/public/media/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PoliciesRoute: typeof PoliciesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ASplatRoute: typeof ASplatRoute
  ApiPublicHooksAnnounceRoute: typeof ApiPublicHooksAnnounceRoute
  ApiPublicHooksDeliverRoute: typeof ApiPublicHooksDeliverRoute
  ApiPublicHooksHeartbeatRoute: typeof ApiPublicHooksHeartbeatRoute
  ApiPublicHooksRecoverRoute: typeof ApiPublicHooksRecoverRoute
  ApiPublicHooksSupportBotRoute: typeof ApiPublicHooksSupportBotRoute
  ApiPublicHooksSyncRoute: typeof ApiPublicHooksSyncRoute
  ApiPublicHooksTelegramRoute: typeof ApiPublicHooksTelegramRoute
  ApiPublicMediaSplatRoute: typeof ApiPublicMediaSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/a/$': {
      id: '/a/$'
      path: '/a/$'
      fullPath: '/a/$'
      preLoaderRoute: typeof ASplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/announce': {
      id: '/api/public/hooks/announce'
      path: '/api/public/hooks/announce'
      fullPath: '/api/public/hooks/announce'
      preLoaderRoute: typeof ApiPublicHooksAnnounceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/deliver': {
      id: '/api/public/hooks/deliver'
      path: '/api/public/hooks/deliver'
      fullPath: '/api/public/hooks/deliver'
      preLoaderRoute: typeof ApiPublicHooksDeliverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/heartbeat': {
      id: '/api/public/hooks/heartbeat'
      path: '/api/public/hooks/heartbeat'
      fullPath: '/api/public/hooks/heartbeat'
      preLoaderRoute: typeof ApiPublicHooksHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/recover': {
      id: '/api/public/hooks/recover'
      path: '/api/public/hooks/recover'
      fullPath: '/api/public/hooks/recover'
      preLoaderRoute: typeof ApiPublicHooksRecoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/support-bot': {
      id: '/api/public/hooks/support-bot'
      path: '/api/public/hooks/support-bot'
      fullPath: '/api/public/hooks/support-bot'
      preLoaderRoute: typeof ApiPublicHooksSupportBotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync': {
      id: '/api/public/hooks/sync'
      path: '/api/public/hooks/sync'
      fullPath: '/api/public/hooks/sync'
      preLoaderRoute: typeof ApiPublicHooksSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/telegram': {
      id: '/api/public/hooks/telegram'
      path: '/api/public/hooks/telegram'
      fullPath: '/api/public/hooks/telegram'
      preLoaderRoute: typeof ApiPublicHooksTelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/media/$': {
      id: '/api/public/media/$'
      path: '/api/public/media/$'
      fullPath: '/api/public/media/$'
      preLoaderRoute: typeof ApiPublicMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PoliciesRoute: PoliciesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ASplatRoute: ASplatRoute,
  ApiPublicHooksAnnounceRoute: ApiPublicHooksAnnounceRoute,
  ApiPublicHooksDeliverRoute: ApiPublicHooksDeliverRoute,
  ApiPublicHooksHeartbeatRoute: ApiPublicHooksHeartbeatRoute,
  ApiPublicHooksRecoverRoute: ApiPublicHooksRecoverRoute,
  ApiPublicHooksSupportBotRoute: ApiPublicHooksSupportBotRoute,
  ApiPublicHooksSyncRoute: ApiPublicHooksSyncRoute,
  ApiPublicHooksTelegramRoute: ApiPublicHooksTelegramRoute,
  ApiPublicMediaSplatRoute: ApiPublicMediaSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
