// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { brokeredPreviewStorage } from "./previewAuthStorage";

const SUPABASE_URL = "https://bkcgjsliqsayprxdmwyn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJrY2dqc2xpcXNheXByeGRtd3luIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODYyMTA4NjAsImV4cCI6MjEwMTc4Njg2MH0.xGDR4rTw_UY1pJRIIGDtDEM4A1MwiP6VR0hWO6WYjSo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
  },
});
